name: DevOps CI/CD

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env: { APP_ENV: production }
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensures full repo checkout

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with: { node-version: 18 }
      - run: npm install && npm test

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: echo "Deploying..."
